### ISSUE TITLE
US26 - Eu, como usuário, desejo ter uma página de criação de projetos

### ISSUE THREAD

**Issue by sudjoao** [DiProjOrcestra/orclamp#34]
## Descrição da Issue
Tela para criação de projetos.

### Tasks: 
- [x] Criar tela de acordo com o protótipo;
- [x] Pegar nome, descrição, labels e imagem do projeto.

**Comment by fellipe-araujo** [comment]
Já foi feito a Tela de Criação de Projetos para WEB, issue #4
